import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// NOTE: Assuming Panel and Navbar are correctly imported from the UI folder structure
import Panel from "@/app/ui/panel";
import Navbar from "./ui/navbar";
import ChatContainer from "./ui/chatContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tubes RPL",
  description: "Generated by create next app",
};

// IMPORTANT: Updated the function signature to accept named slots (calendar and chat)
export default function RootLayout({
  children,
  calendar,
  chat,
  title,
}: Readonly<{
  children: React.ReactNode;
  calendar: React.ReactNode; // Named slot type definition
  chat: React.ReactNode;     // Named slot type definition
  title: string;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[#e8f1ff]`}
      >
        <div className="min-h-screen flex flex-col">

          <Navbar />

          <main className="p-8 bg-[#6ec0ff] grow flex flex-col">

            <h1 className="text-5xl font-extrabold text-white mb-6">{title}</h1>

            {/* START: Grid Layout Implementation */}

            {/* Set the grid template columns to define fixed widths for the side columns */}
            <div
              className="grid grid-cols-[350px_1fr_300px] gap-6 grow"
            >

              {/* Calendar Column - Now renders the 'calendar' named slot content */}
              <div className="flex flex-col">
                <Panel>

                  <h2 className="text-2xl font-bold mb-4">Calendar</h2>
                  <div className="bg-white p-3 rounded-lg shadow border-l-4 border-blue-500">
                    <p className="font-semibold">Today's Focus:</p>
                    <p className="text-sm text-gray-600">Complete Module 3 Quiz</p>
                  </div>
                  <div className="bg-white p-3 rounded-lg shadow border-l-4 border-yellow-500">
                    <p className="font-semibold">Upcoming Due Date:</p>
                    <p className="text-sm text-gray-600">Project Proposal (Friday)</p>
                  </div>
                  <div className="flex justify-center mt-auto p-4">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition duration-150">
                      View Full Schedule
                    </button>
                  </div>‰
                </Panel>
              </div>

              {/* Course Column - Renders the default 'children' (page) content */}
              <div className="flex flex-col">
                <Panel>

                  {children}
                </Panel>
              </div>

              {/* Chat Column - Now renders the 'chat' named slot content */}
              <div className="flex flex-col">
                <Panel>




                  <div className="flex flex-col grow p-2">
                    <h2 className="text-2xl font-bold mb-4">Chat</h2>

                    <ChatContainer />

                  </div>


                </Panel>
              </div>
            </div>
            {/* END: Grid Layout Implementation */}

          </main>
        </div>
      </body>
    </html>
  );
}
